//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GentelellaTemplate.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class BITACORA
    {
        public System.DateTime FECHA_HORA { get; set; }
        public string DESCRIPCION_ERROR { get; set; }
        public long CODIGO_ERROR { get; set; }
        public string ORIGEN { get; set; }
        public long CONSECUTIVO { get; set; }
        public string CORREO_USUARIO { get; set; }
    
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
