//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GentelellaTemplate.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANDIDATOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CANDIDATOS()
        {
            this.SOLICITUDES = new HashSet<SOLICITUDES>();
        }
    
        public string NOMBRE_CANDIDATO { get; set; }
        public string APELLIDO_CANDIDATO { get; set; }
        public int EXP_CANDIDATO { get; set; }
        public string GRADO_ESTUDIO { get; set; }
        public int TELEFONO_CANDIDATO { get; set; }
        public long AREA_INTERES { get; set; }
        public string CORREO_USUARIO { get; set; }
    
        public virtual CATEGORIAS CATEGORIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUDES> SOLICITUDES { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
