//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GentelellaTemplate.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEOS()
        {
            this.SOLICITUDES = new HashSet<SOLICITUDES>();
        }
    
        public long ID_EMPLEO { get; set; }
        public long ID_CATEGORIA { get; set; }
        public int EXP_MINIMA { get; set; }
        public string GRADO_ESTUDIO { get; set; }
        public string COMPANIA { get; set; }
        public string EMPLEO_NOMBRE { get; set; }
        public string ESTADO_PUESTO { get; set; }
        public string DESCRIPCION { get; set; }
        public string REQUISITOS { get; set; }
        public string CORREO_RECLUTADOR { get; set; }
    
        public virtual CATEGORIAS CATEGORIAS { get; set; }
        public virtual RECLUTADORES RECLUTADORES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUDES> SOLICITUDES { get; set; }
    }
}
