//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GentelellaTemplate.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECLUTADORES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RECLUTADORES()
        {
            this.EMPLEOS = new HashSet<EMPLEOS>();
        }
    
        public string CORREO_RECLUTADOR { get; set; }
        public string NOMBRE_RECLUTADOR { get; set; }
        public string APELLIDO_RECLUTADOR { get; set; }
        public string COMPANIA { get; set; }
        public int TELEFONO_RECLUTADOR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEOS> EMPLEOS { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
