//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPrograAvnzd.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class BITACORA
    {
        public System.DateTime FECHA_HORA { get; set; }
        public string DESCRIPCION_ERROR { get; set; }
        public long CODIGO_ERROR { get; set; }
        public string ORIGEN { get; set; }
        public long CONSECUTIVO { get; set; }
        public string CORREO_USUARIO { get; set; }
    
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
