//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPrograAvnzd.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEOS()
        {
            this.SOLICITUDES = new HashSet<SOLICITUDES>();
        }
    
        public long ID_EMPLEO { get; set; }
        public long ID_CATEGORIA { get; set; }
        public int EXP_MINIMA { get; set; }
        public string GRADO_ESTUDIO { get; set; }
        public string COMPANIA { get; set; }
        public string EMPLEO_NOMBRE { get; set; }
        public string ESTADO_PUESTO { get; set; }
        public string DESCRIPCION { get; set; }
        public string REQUISITOS { get; set; }
        public string CORREO_RECLUTADOR { get; set; }
    
        public virtual CATEGORIAS CATEGORIAS { get; set; }
        public virtual RECLUTADORES RECLUTADORES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUDES> SOLICITUDES { get; set; }
    }
}
