//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPrograAvnzd.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECLUTADORES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RECLUTADORES()
        {
            this.EMPLEOS = new HashSet<EMPLEOS>();
        }
    
        public string CORREO_RECLUTADOR { get; set; }
        public string NOMBRE_RECLUTADOR { get; set; }
        public string APELLIDO_RECLUTADOR { get; set; }
        public string COMPANIA { get; set; }
        public int TELEFONO_RECLUTADOR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEOS> EMPLEOS { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
