//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPrograAvnzd.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUDES
    {
        public long ID_SOLICITUD { get; set; }
        public long ID_EMPLEO { get; set; }
        public string CORREO_CANDIDATO { get; set; }
        public System.DateTime FECHA_SOLICITUD { get; set; }
    
        public virtual CANDIDATOS CANDIDATOS { get; set; }
        public virtual EMPLEOS EMPLEOS { get; set; }
    }
}
