//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPrograAvnzd.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIOS()
        {
            this.BITACORA = new HashSet<BITACORA>();
        }
    
        public string CORREO_USUARIO { get; set; }
        public string CONTRASENA { get; set; }
        public long ID_ROL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BITACORA> BITACORA { get; set; }
        public virtual CANDIDATOS CANDIDATOS { get; set; }
        public virtual RECLUTADORES RECLUTADORES { get; set; }
        public virtual ROLES ROLES { get; set; }
    }
}
